src/HolyOdesaWood/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
# from HolyOdesaWood import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, dociment_root=settings.MEDIA_ROOT)

src/market/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.contrib import admin

from .views import index, contacts, about, product_details_default

app_name = 'market'
urlpatterns = [

    # path('', views.HomePageView.as_view(), name='home_page'),
    path('',          index,                   name='index'),
    path('contacts/', contacts,                name='contacts'),
    path('about/',    about,                   name='about'),
    path('shop/',     product_details_default, name='product_details_default'),
    # path('admin/',    admin.site.urls, name='admin')

    # path('cinemas/', views.CinemasListView.as_view(), name='cinemas_list'),
    # path('cinemas/<slug:slug>/', views.CinemaDescriptionView.as_view(), name='cinema_description'),
    # path('cinemas/<slug:cinema_slug>/<int:hall_number>/', views.hall_description_view, name='hall_description'),
    #
    # path('about/', views.AboutView.as_view(), name='about'),
]

src/market/models.py
from django.db import models


class Item(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/")
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)

src/market/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import HttpResponse


# Create your views here.

# class HomePageView(ListView):
#
#     template_name = 'market/templates/index.html'

def index(request):
    return render(request, 'market/index.html')


def about(request):
    return render(request, 'market/about-us.html')


def product_details_default(request):
    return render(request, 'market/product-details-default.html')


def contacts(request):
    return render(request, 'market/contact-us.html')

src/market/templates/market/footer.html
{% load static %}
<footer class="footer-section section-top-gap-100">
    <!-- Start Footer Top Area -->
    <div class="footer-top section-inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-5">
                    <div class="footer-widget footer-widget-contact">
                        <div class="footer-logo">
                            <a href="index.html"><img src="../../static/market/images/logo/logo.png" alt="" class="img-fluid"></a>
                        </div>
                        <div class="footer-contact">
                            <p>We are a team of designers and developers that create high quality Magento, Prestashop, Opencart...</p>
                            <div class="customer-support">
                                <div class="customer-support-icon">
                                    <img src="../../static/market/images/icon/support-icon.png" alt="">
                                </div>
                                <div class="customer-support-text">
                                    <span>Customer Support</span>
                                    <a class="customer-support-text-phone" href="tel:(08)123456789">(08) 123 456 789</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-7">
                    <div class="footer-widget footer-widget-subscribe">
                        <h3 class="footer-widget-title">Subscribe newsletter to get updated</h3>
                        <form action="#" method="post">
                            <div class="footer-subscribe-box default-search-style d-flex">
                                <label>
                                    <input class="default-search-style-input-box border-around border-right-none subscribe-form" type="email" placeholder="Search entire store here ..." required>
                                </label>
                                <button class="default-search-style-input-btn" type="submit">Subscribe</button>
                            </div>
                        </form>
                        <p class="footer-widget-subscribe-note">We’ll never share your email address <br> with a third party.</p>
                        <ul class="footer-social">
                            <li><a href="" class="facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="" class="youtube"><i class="fa fa-youtube"></i></a></li>
                            <li><a href="" class="pinterest"><i class="fa fa-pinterest"></i></a></li>
                            <li><a href="" class="instagram"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="footer-widget footer-widget-menu">
                        <h3 class="footer-widget-title">Information</h3>
                        <div class="footer-menu">
                            <ul class="footer-menu-nav">
                                <li><a href="">Delivery</a></li>
                                <li><a href="about-us.html">About Us</a></li>
                                <li><a href="contact-us.html">Contact us</a></li>
                                <li><a href="">Stores</a></li>
                            </ul>
                            <ul class="footer-menu-nav">
                                <li><a href="">Legal Notice</a></li>
                                <li><a href="">Secure payment</a></li>
                                <li><a href="">Sitemap</a></li>
                                <li><a href="my-account.html">My Account</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Footer Top Area -->
    <!-- Start Footer Bottom Area -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="copyright-area">
                        <p class="copyright-area-text">Copyright © 2020 <a class="copyright-link" href="https://hasthemes.com/">Hasthemes</a></p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="footer-payment">
                        <a href=""><img class="img-fluid" src="../../static/market/images/icon/payment-icon.png" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Footer Bottom Area -->
</footer> <!-- ...:::: End Footer Section:::... -->

src/market/templates/market/header.html
{% load static %}
<header class="header-section d-lg-block d-none">
        <!-- Start Header Top Area -->
        {% comment %}<div class="header-top">
            <div class="container">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-6">
                        <div class="header-top--left">
                            <span>Вітаємо до нашого магазину!</span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="header-top--right">
                            <!-- Start Header Top Menu -->
                            <ul class="header-user-menu">
                                <li class="has-user-dropdown">
                                    <a href="">Setting</a>
                                    <!-- Header Top Menu's Dropdown -->
                                    <ul class="user-sub-menu">
                                        <li><a href="">Checkout</a></li>
                                        <li><a href="">My Account</a></li>
                                        <li><a href="">Shopping Cart</a></li>
                                        <li><a href="">Wishlist</a></li>
                                    </ul>
                                </li>
                                <li class="has-user-dropdown">
                                    <a href="">$ USD</a>
                                    <!-- Header Top Menu's Dropdown -->
                                    <ul class="user-sub-menu">
                                        <li><a href="">EUR – Euro</a></li>
                                        <li><a href="">GBP – British Pound</a></li>
                                        <li><a href="">INR – India Rupee</a></li>
                                    </ul>
                                </li>
                                <li class="has-user-dropdown">
                                    <a href="">English</a>
                                    <!-- Header Top Menu's Dropdown -->
                                    <ul class="user-sub-menu">
                                        <li><a href=""><img class="user-sub-menu-in-icon" src="../../static/market/images/icon/lang-en.png" alt=""> English</a></li>
                                        <li><a href=""><img class="user-sub-menu-in-icon" src="../../static/market/images/icon/lang-gr.png" alt=""> Germany</a></li>
                                    </ul>
                                </li>
                                <li><a href=""><i class="icon-repeat"></i> Compare (0)</a></li>
                            </ul> <!-- End Header Top Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </div>{% endcomment %} <!-- End Header Top Area -->

        <!-- Start Header Center Area -->
        <div class="header-center">
            <div class="container">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-3">
                        <!-- Logo Header -->
                        <div class="header-logo">
                            <a href="index.html"><img src="../../static/market/images/logo/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-6">
                        <!-- Start Header Search -->
                        <div class="header-search">
                            <form action="#" method="post">
                                <div class="header-search-box default-search-style d-flex">
                                    <input class="default-search-style-input-box border-around border-right-none" type="search" placeholder="Пошук по всьому магазину ..." required>
                                    <button class="default-search-style-input-btn" type="submit"><i class="icon-search"></i></button>
                                </div>
                            </form>
                        </div> <!-- End Header Search -->
                    </div>
                    <div class="col-3 text-right">
                        <!-- Start Header Action Icon -->
                        <ul class="header-action-icon">
                            <li>
                                <a href="#offcanvas-wishlish" class="offcanvas-toggle">
                                    <i class="icon-heart"></i>
                                    <span class="header-action-icon-item-count">3</span>
                                </a>
                            </li>
                            <li>
                                <a href="#offcanvas-add-cart" class="offcanvas-toggle">
                                    <i class="icon-shopping-cart"></i>
                                    <span class="header-action-icon-item-count">3</span>
                                </a>
                            </li>
                        </ul> <!-- End Header Action Icon -->
                    </div>
                </div>
            </div>
        </div> <!-- End Header Center Area -->

        <!-- Start Bottom Area -->
        <div class="header-bottom sticky-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Header Main Menu -->
                        <div class="main-menu">
                            <nav>
                                <ul>
                                    <li class="has-dropdown">
                                        <a class="active main-menu-link" href="{% url 'market:index' %}">Головна</a>
{#                                        <a class="active main-menu-link" href="index.html">Головна</a>#}
                                    </li>
                                    <li class="has-dropdown has-megaitem">
                                        <a href="{% url 'market:product_details_default' %}">Магазин <i class="fa fa-angle-down"></i></a>
                                        <!-- Mega Menu -->
{#                                        <div class="mega-menu">#}
{#                                            <ul class="mega-menu-inner">#}
{#                                                <!-- Mega Menu Sub Link -->#}
{#                                                <li class="mega-menu-item">#}
{#                                                    <a href="#" class="mega-menu-item-title">Shop Layouts</a>#}
{#                                                    <ul class="mega-menu-sub">#}
{#                                                        <li><a href="shop-grid-sidebar-left.html">Grid Left Sidebar</a></li>#}
{#                                                        <li><a href="shop-grid-sidebar-right.html">Grid Right Sidebar</a></li>#}
{#                                                        <li><a href="shop-full-width.html">Full Width</a></li>#}
{#                                                        <li><a href="shop-list-sidebar-left.html">List Left Sidebar</a></li>#}
{#                                                        <li><a href="shop-list-sidebar-right.html">List Right Sidebar</a></li>#}
{#                                                    </ul>#}
{#                                                </li>#}
{#                                                <!-- Mega Menu Sub Link -->#}
{#                                                <li class="mega-menu-item">#}
{#                                                    <a href="#" class="mega-menu-item-title">Other Pages</a>#}
{#                                                    <ul class="mega-menu-sub">#}
{#                                                        <li><a href="cart.html">Cart</a></li>#}
{#                                                        <li><a href="wishlist.html">Wishlist</a></li>#}
{#                                                        <li><a href="compare.html">Compare</a></li>#}
{#                                                        <li><a href="checkout.html">Checkout</a></li>#}
{#                                                        <li><a href="login.html">Login</a></li>#}
{#                                                        <li><a href="my-account.html">My Account</a></li>#}
{#                                                    </ul>#}
{#                                                </li>#}
{#                                                <!-- Mega Menu Sub Link -->#}
{#                                                <li class="mega-menu-item">#}
{#                                                    <a href="#" class="mega-menu-item-title">Product Types</a>#}
{#                                                    <ul class="mega-menu-sub">#}
{#                                                        <li><a href="product-details-default.html">Product Default</a></li>#}
{#                                                        <li><a href="product-details-variable.html">Product Variable</a></li>#}
{#                                                        <li><a href="product-details-affiliate.html">Product Referral</a></li>#}
{#                                                        <li><a href="product-details-group.html">Product Group</a></li>#}
{#                                                        <li><a href="product-details-single-slide.html">Product Slider</a></li>#}
{#                                                    </ul>#}
{#                                                </li>#}
{#                                                <!-- Mega Menu Sub Link -->#}
{#                                                <li class="mega-menu-item">#}
{#                                                    <a href="#" class="mega-menu-item-title">Product Types</a>#}
{#                                                    <ul class="mega-menu-sub">#}
{#                                                        <li><a href="product-details-tab-left.html">Product Tab Left</a></li>#}
{#                                                        <li><a href="product-details-tab-right.html">Product Tab Right</a></li>#}
{#                                                        <li><a href="product-details-gallery-left.html">Product Gallery Left</a></li>#}
{#                                                        <li><a href="product-details-gallery-right.html">Product Gallery Right</a></li>#}
{#                                                        <li><a href="product-details-sticky-left.html">Product Sticky Left</a></li>#}
{#                                                        <li><a href="product-details-sticky-right.html">Product Sticky right</a></li>#}
{#                                                    </ul>#}
{#                                                </li>#}
{#                                            </ul>#}
{#                                            <div class="menu-banner">#}
{#                                                <a href="" class="menu-banner-link">#}
{#                                                    <img class="menu-banner-img" src="../../static/market/images/banner/menu-banner.jpg" alt="">#}
{#                                                </a>#}
{#                                            </div>#}
{#                                        </div>#}
                                    </li>
                                    {% comment %}<li class="has-dropdown">
                                        <a href="blog-single-sidebar-left.html">Blog <i class="fa fa-angle-down"></i></a>
                                        <!-- Sub Menu -->
                                        <ul class="sub-menu">
                                            <li><a href="blog-grid-sidebar-left.html">Blog Grid Sidebar left</a></li>
                                            <li><a href="blog-grid-sidebar-right.html">Blog Grid Sidebar Right</a></li>
                                            <li><a href="blog-full-width.html">Blog Full Width</a></li>
                                            <li><a href="blog-single-sidebar-left.html">Blog Single Sidebar left</a></li>
                                            <li><a href="blog-single-sidebar-right.html">Blog Single Sidebar Right</a></li>
                                        </ul>
                                    </li>{% endcomment %}
                                    {% comment %}<li class="has-dropdown">
                                        <a href="#">Pages <i class="fa fa-angle-down"></i></a>
                                        <!-- Sub Menu -->
                                        <ul class="sub-menu">
                                            <li><a href="service.html">Service</a></li>
                                            <li><a href="faq.html">Frequently Questions</a></li>
                                            <li><a href="privacy-policy.html">Privacy Policy</a></li>
                                            <li><a href="404.html">404 Page</a></li>
                                        </ul>
                                    </li>{% endcomment %}
                                    <li>
                                        <a href="{% url 'market:about' %}">Про нас</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'market:contacts' %}">Контакти</a>
                                    </li>
                                </ul>
                            </nav>
                        </div> <!-- Header Main Menu Start -->
                    </div>
                </div>
            </div>
        </div> <!-- End Bottom Area -->
    </header>